version: 2
updates:
    - package-ecosystem: "gomod" # See documentation for possible values
      directory: "/" # Location of package manifests
      schedule:
          interval: "weekly"
        #   day: "monday"
        #   time: "08:00"
      cooldown:
          default-days: 30
          semver-major-days: 30
          semver-minor-days: 14
          semver-patch-days: 14
